### ISSUE TITLE
question about libstorage

### ISSUE THREAD

**Issue by allspace** [openSUSE/libstorage#119]
Is this libstoragemgmt which is shipped in RHEL/CentOS 7.0? or this is another storage management framework on Linux?

**Comment by aschnell** [comment]
This libstorage is something different.

**Comment by mvidner** [comment]
@allspace Perhaps you were looking for https://github.com/libstorage/libstoragemgmt ?
This one is described at https://en.opensuse.org/Portal:Libstorage .

**Comment by allspace** [comment]
Thank you mvidner. You answered my question.
